apiVersion: v2
appVersion: '1.0'
description: A Helm chart for expressjs-monorepo-template crons
name: expressjs-monorepo-template-crons
annotations:
  team: dtsse
home: https://github.com/hmcts/dtsse-expressjs-monorepo-template
version: 0.0.1
dependencies:
  - name: job
    version: 2.2.0
    repository: 'oci://hmctsprod.azurecr.io/helm'
