global:
  jobKind: CronJob
  enableKeyVaults: true
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
job:
  releaseNameOverride: "{{ .Release.Name }}-crons"
  disableActiveClusterCheck: true
  image: hmctspublic.azurecr.io/dtsse/expressjs-monorepo-template-crons:latest
  aadIdentityName: dtsse
  environment:
    SCRIPT_NAME: 'example'
  keyVaults:
    dtsse:
      secrets:
        - name: AppInsightsConnectionString
          alias: APPLICATION_INSIGHTS_CONNECTION_STRING
        - name: db-url
          alias: DATABASE_URL
  schedule: "0 0/10 * * *" # this is just a placeholder, configure in your flux
  concurrencyPolicy: Forbid

