global:
  jobKind: CronJob
  enableKeyVaults: true
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
job:
  disableActiveClusterCheck: true
  image: hmctspublic.azurecr.io/dtsse/expressjs-monorepo-template-crons:latest
  aadIdentityName: dtsse
  environment:
    DATABASE_URL: 'postgresql://user:password@postgres:5432/database'
    SCRIPT_NAME: 'example'
  keyVaults:
    dtsse:
      secrets:
        - app-insights-connection-string
        - dynatrace-url
  schedule: "0 0/10 * * *" # this is just a placeholder, configure in your flux
  concurrencyPolicy: Forbid

