apiVersion: v2
appVersion: '1.0'
description: Prisma Studio service with migration runner for expressjs-monorepo-template
name: expressjs-monorepo-template-postgres
annotations:
  team: dtsse
home: https://github.com/hmcts/dtsse-expressjs-monorepo-template
version: 0.0.1
dependencies:
  - name: nodejs
    version: 3.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
