apiVersion: v2
appVersion: '1.0'
description: Database migration job for expressjs-monorepo-template
name: expressjs-monorepo-template-postgres
annotations:
  team: dtsse
home: https://github.com/hmcts/dtsse-expressjs-monorepo-template
version: 0.0.1
dependencies:
  - name: job
    version: 2.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
