global:
  jobKind: Job
  enableKeyVaults: true
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

job:
  releaseNameOverride: "{{ .Release.Name }}-postgres"
  image: hmctspublic.azurecr.io/dtsse/expressjs-monorepo-template-postgres:latest
  aadIdentityName: dtsse
  keyVaults:
    dtsse:
      secrets:
        - name: db-url
          alias: DATABASE_URL
  backoffLimit: 2
  restartPolicy: Never
