nodejs:
  applicationPort: 3001
  aadIdentityName: dtsse
  ingressHost: expressjs-monorepo-template-api.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/dtsse/expressjs-monorepo-template-api:latest'
  environment:
    EXAMPLE_ENV: example
  keyVaults:
    dtsse:
      secrets:
        - name: AppInsightsConnectionString
          alias: APPLICATION_INSIGHTS_CONNECTION_STRING
        - name: db-url
          alias: DATABASE_URL
