nodejs:
  applicationPort: 3001
  aadIdentityName: dtsse
  ingressHost: expressjs-monorepo-template-api.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/dtsse/expressjs-monorepo-template-api:latest'
  environment:
    REDIS_HOST: 'dtsse-redis-{{ .Values.global.environment }}.redis.cache.windows.net'
  keyVaults:
    dtsse:
      secrets:
        - redis-access-key
        - app-insights-connection-string
        - dynatrace-url
