nodejs:
  releaseNameOverride: "{{ .Release.Name }}-web"
  applicationPort: 3000
  aadIdentityName: dtsse
  ingressHost: expressjs-monorepo-template-web.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/dtsse/expressjs-monorepo-template-web:latest'
  environment:
    REDIS_URL: 'redis://dtsse-{{ .Values.global.environment }}.redis.cache.windows.net:6379'
  keyVaults:
    dtsse:
      secrets:
        - name: AppInsightsConnectionString
          alias: APPLICATION_INSIGHTS_CONNECTION_STRING
        - name: db-url
          alias: DATABASE_URL
