nodejs:
  releaseNameOverride: "{{ .Release.Name }}-web"
  applicationPort: 3000
  aadIdentityName: dtsse
  ingressHost: expressjs-monorepo-template-web.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/dtsse/expressjs-monorepo-template-web:latest'
  keyVaults:
    dtsse:
      secrets:
        - name: ExpressJsAppInsightsConnectionString
          alias: APPLICATION_INSIGHTS_CONNECTION_STRING
        - name: db-url
          alias: DATABASE_URL
        - name: redis-url
          alias: REDIS_URL
