nodejs:
  releaseNameOverride: "{{ .Release.Name }}-web"
  applicationPort: 3000
  aadIdentityName: dtsse
  ingressHost: expressjs-monorepo-template-web.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctsprod.azurecr.io/dtsse/expressjs-monorepo-template-web:latest'
  environment:
    POSTGRES_DATABASE: expressjs-monorepo-template
  keyVaults:
    dtsse:
      secrets:
        - name: ExpressJsAppInsightsConnectionString
          alias: APPLICATION_INSIGHTS_CONNECTION_STRING
        - name: redis-url
          alias: REDIS_URL
        - name: postgres-host
          alias: POSTGRES_HOST
        - name: postgres-user
          alias: POSTGRES_USER
        - name: postgres-password
          alias: POSTGRES_PASSWORD
        - name: postgres-port
          alias: POSTGRES_PORT
