name: Helm Deploy Job

on:
  workflow_call:
    inputs:
      change-id:
        required: true
        type: string
        description: "PR number or change identifier"
      timestamp:
        required: true
        type: string
        description: "Build timestamp for image tagging"
      short-sha:
        required: true
        type: string
        description: "Short git SHA for image tagging"
      affected-apps:
        required: true
        type: string
        description: "JSON array of affected apps"
      helm-apps:
        required: true
        type: string
        description: "JSON array of all Helm apps"
    outputs:
      preview-urls:
        description: "Base64-encoded JSON of preview URLs"
        value: ${{ jobs.helm-deploy.outputs.preview-urls }}

env:
  CHANGE_ID: ${{ inputs.change-id }}
  REGISTRY: hmctspublic.azurecr.io
  AZURE_TENANT_ID: 531ff96d-0ae9-462a-8d2d-bec7c0b42082

jobs:
  helm-deploy:
    name: Deploy to Preview
    runs-on: ubuntu-latest
    environment:
      name: preview
    outputs:
      preview-urls: ${{ steps.preview-urls.outputs.urls }}
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set environment variables
        run: |
          # Read metadata from root Helm chart
          CHART_PATH="helm/expressjs-monorepo-template/Chart.yaml"
          TEAM_NAME=$(grep -A 1 'annotations:' "$CHART_PATH" | grep 'team:' | awk '{print $2}' | tr -d '"')
          APPLICATION_NAME=$(grep '^name:' "$CHART_PATH" | awk '{print $2}' | tr -d '"')
          GIT_REPO=$(git config --get remote.origin.url | sed 's/git@github.com:/https:\/\/github.com\//' | sed 's/\.git$//')

          echo "TEAM_NAME=${TEAM_NAME}" >> $GITHUB_ENV
          echo "APPLICATION_NAME=${APPLICATION_NAME}" >> $GITHUB_ENV
          echo "GIT_REPO=${GIT_REPO}" >> $GITHUB_ENV
          echo "TIMESTAMP=${{ inputs.timestamp }}" >> $GITHUB_ENV
          echo "SHORT_SHA=${{ inputs.short-sha }}" >> $GITHUB_ENV

          # Set dynamic image variables and release name
          .github/workflows/jobs/build-and-publish-images/set-image-variables.sh \
            '${{ inputs.affected-apps }}' \
            '${{ inputs.helm-apps }}' \
            '${{ env.CHANGE_ID }}' \
            '${{ inputs.short-sha }}' \
            '${{ inputs.timestamp }}' \
            "${APPLICATION_NAME}"

      - name: Deploy preview environment
        id: deploy
        uses: hmcts/cnp-githubactions-library/helm-deploy@helm-deploy
        with:
          # TODO combine these two
          cluster-name: cft-preview-01-aks
          resource-group: cft-preview-01-rg
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS_CFT_PREVIEW }}
          release-name: ${{ env.RELEASE_NAME }}
          namespace: ${{ env.TEAM_NAME }}
          chart: helm/${{ env.APPLICATION_NAME }}
          values-template: helm/${{ env.APPLICATION_NAME }}/values.preview.template.yaml
          subchart-paths: apps/*/helm
          set: |
            global.tenantId=${{ env.AZURE_TENANT_ID }}
            global.environment=aat
            global.enableKeyVaults=true
            global.devMode=true
            global.disableTraefikTls=false
            global.tags.teamName=${{ env.TEAM_NAME }}
            global.tags.applicationName=${{ env.APPLICATION_NAME }}
            global.tags.builtFrom=${{ env.GIT_REPO }}
            global.tags.businessArea=CFT
            global.tags.environment=development
          oci-registry: ${{ env.REGISTRY }}
          oci-username: ${{ secrets.REGISTRY_USERNAME }}
          oci-password: ${{ secrets.REGISTRY_PASSWORD }}

# TODO can this be an output of the deploy
      - name: Get preview URLs from ingress
        id: preview-urls
        run: |
          # Get URLs and base64 encode to avoid special character issues in GitHub Actions
          URLS_JSON=$(.github/workflows/jobs/pr-comment/get-preview-urls.sh "${{ env.TEAM_NAME }}" "${{ env.RELEASE_NAME }}")
          URLS_B64=$(echo -n "${URLS_JSON}" | base64 -w 0)
          echo "urls=${URLS_B64}" >> "$GITHUB_OUTPUT"
